In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array([0.02, 0.12, 0.19, 0.27, 0.47, 0.51, 0.64, 0.84, 0.88, 0.99])
t = np.array([0.05, 0.87, 0.94, 0.92, 0.54, -0.11, -0.78, -0.89, -0.79, -0.04])

In [4]:
def phi(X,m):
    return [X**i for i in range(m)]

In [9]:
#np.array([phi(x, m=3) for x in X])

In [7]:
PHI = np.array([phi(x, m=4) for x in X])

In [8]:
PHI

array([[  1.00000000e+00,   2.00000000e-02,   4.00000000e-04,
          8.00000000e-06],
       [  1.00000000e+00,   1.20000000e-01,   1.44000000e-02,
          1.72800000e-03],
       [  1.00000000e+00,   1.90000000e-01,   3.61000000e-02,
          6.85900000e-03],
       [  1.00000000e+00,   2.70000000e-01,   7.29000000e-02,
          1.96830000e-02],
       [  1.00000000e+00,   4.70000000e-01,   2.20900000e-01,
          1.03823000e-01],
       [  1.00000000e+00,   5.10000000e-01,   2.60100000e-01,
          1.32651000e-01],
       [  1.00000000e+00,   6.40000000e-01,   4.09600000e-01,
          2.62144000e-01],
       [  1.00000000e+00,   8.40000000e-01,   7.05600000e-01,
          5.92704000e-01],
       [  1.00000000e+00,   8.80000000e-01,   7.74400000e-01,
          6.81472000e-01],
       [  1.00000000e+00,   9.90000000e-01,   9.80100000e-01,
          9.70299000e-01]])

In [12]:
w = np.linalg.solve(np.dot(PHI.T, PHI), np.dot(PHI.T, t))

In [14]:
w

array([ -0.18034286,  12.00494583, -34.3075481 ,  22.56306413])

In [15]:
def f(w, x):
    return np.dot(w, phi(x, m=4))

In [ ]:
xlist = np.arange(0,  1, 0.01)
ylist = [f(w,x) for x in xlist]
plt.plot(xlist, ylist)
plt.plot(X, t, 'o')
plt.show()

In [1]:
#sample
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b = np.array([[9],[8],[7]])

In [15]:
b

array([[9],
       [8],
       [7]])

In [20]:
np.linalg.solve(a,b)

array([[  1.53333333],
       [-13.06666667],
       [ 11.2       ]])

In [21]:
b = np.array([[1,4,3],[7,5,6],[9,8,9]])

In [22]:
a - b

array([[ 0, -2,  0],
       [-3,  0,  0],
       [-2,  0,  0]])

In [23]:
def sample(a,b):
    c = a * b
    def f(A):
        return 10 * A
    return f, c

In [24]:
a = 10

In [25]:
b = 20

In [26]:
sample(10,20)

(<function __main__.f>, 200)

In [27]:
'''
if __name__ == '__main__':
    train_set = create_dataset(N)
    test_set = create_dataset(N)
    df_ws = DataFrame()

    # 多項式近似の曲線を求めて表示
    fig = plt.figure()
    for c, m in enumerate(M):
        f, ws = resolve(train_set, m)
        df_ws = df_ws.append(Series(ws,name="M=%d" % m))

        subplot = fig.add_subplot(2,2,c+1)
        subplot.set_xlim(-0.05,1.05)
        subplot.set_ylim(-1.5,1.5)
        subplot.set_title("M=%d" % m)

        # トレーニングセットを表示
        subplot.scatter(train_set.x, train_set.y, marker='o', color='blue')

        # 真の曲線を表示
        linex = np.linspace(0,1,101)
        liney = np.sin(2*np.pi*linex)
        subplot.plot(linex, liney, color='green', linestyle='--')

        # 多項式近似の曲線を表示
        linex = np.linspace(0,1,101)
        liney = f(linex)
        label = "E(RMS)=%.2f" % rms_error(train_set, f)
        subplot.plot(linex, liney, color='red', label=label)
        subplot.legend(loc=1)

    # 係数の値を表示
    print "Table of the coefficients"
    print df_ws.transpose()
    fig.show()

    # トレーニングセットとテストセットでの誤差の変化を表示
    df = DataFrame(columns=['Training set','Test set'])
    for m in range(0,10):   # 多項式の次数
        f, ws = resolve(train_set, m)
        train_error = rms_error(train_set, f)
        test_error = rms_error(test_set, f)
        df = df.append(
                Series([train_error, test_error],
                    index=['Training set','Test set']),
                ignore_index=True)
    df.plot(title='RMS Error', style=['-','--'], grid=True, ylim=(0,0.9))
    plt.show()
'''

'\nif __name__ == \'__main__\':\n    train_set = create_dataset(N)\n    test_set = create_dataset(N)\n    df_ws = DataFrame()\n\n    # \xe5\xa4\x9a\xe9\xa0\x85\xe5\xbc\x8f\xe8\xbf\x91\xe4\xbc\xbc\xe3\x81\xae\xe6\x9b\xb2\xe7\xb7\x9a\xe3\x82\x92\xe6\xb1\x82\xe3\x82\x81\xe3\x81\xa6\xe8\xa1\xa8\xe7\xa4\xba\n    fig = plt.figure()\n    for c, m in enumerate(M):\n        f, ws = resolve(train_set, m)\n        df_ws = df_ws.append(Series(ws,name="M=%d" % m))\n\n        subplot = fig.add_subplot(2,2,c+1)\n        subplot.set_xlim(-0.05,1.05)\n        subplot.set_ylim(-1.5,1.5)\n        subplot.set_title("M=%d" % m)\n\n        # \xe3\x83\x88\xe3\x83\xac\xe3\x83\xbc\xe3\x83\x8b\xe3\x83\xb3\xe3\x82\xb0\xe3\x82\xbb\xe3\x83\x83\xe3\x83\x88\xe3\x82\x92\xe8\xa1\xa8\xe7\xa4\xba\n        subplot.scatter(train_set.x, train_set.y, marker=\'o\', color=\'blue\')\n\n        # \xe7\x9c\x9f\xe3\x81\xae\xe6\x9b\xb2\xe7\xb7\x9a\xe3\x82\x92\xe8\xa1\xa8\xe7\xa4\xba\n        linex = np.linspace(0,1,101)\n        l

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import Series, DataFrame
from numpy.random import normal

def create_dataset(num):
    dataset = DataFrame(columns=['x','y'])
    for i in range(num):
        x = float(i)/float(num-1)
        y = np.sin(2*np.pi*x) + normal(scale=0.3)
        dataset = dataset.append(Series([x,y], index=['x','y']),
                                 ignore_index=True)
    return dataset

def rms_error(dataset):
    err = 0.0
    for index, line in dataset.iterrows():
        print index, line
        x, y = line.x, line.y
        print x,y
        #err += 0.5 * (y - f(x))**2
    return err

In [37]:
N=10            
M=[0,1,3,9]
train_set = create_dataset(N)

In [38]:
train_set

x         y
0  0.000000 -0.263050
1  0.111111  0.447216
2  0.222222  1.252177
3  0.333333  0.958030
4  0.444444  0.813036
5  0.555556 -0.173796
6  0.666667 -0.919094
7  0.777778 -0.688628
8  0.888889 -0.638265
9  1.000000  0.071729

In [39]:
rms_error(train_set)

0 x    0.00000
y   -0.26305
Name: 0, dtype: float64
0.0 -0.263049652401
1 x    0.111111
y    0.447216
Name: 1, dtype: float64
0.111111111111 0.447215653894
2 x    0.222222
y    1.252177
Name: 2, dtype: float64
0.222222222222 1.2521768713
3 x    0.333333
y    0.958030
Name: 3, dtype: float64
0.333333333333 0.958030485627
4 x    0.444444
y    0.813036
Name: 4, dtype: float64
0.444444444444 0.813035783992
5 x    0.555556
y   -0.173796
Name: 5, dtype: float64
0.555555555556 -0.173795816426
6 x    0.666667
y   -0.919094
Name: 6, dtype: float64
0.666666666667 -0.919094392605
7 x    0.777778
y   -0.688628
Name: 7, dtype: float64
0.777777777778 -0.688627859332
8 x    0.888889
y   -0.638265
Name: 8, dtype: float64
0.888888888889 -0.638265346649
9 x    1.000000
y    0.071729
Name: 9, dtype: float64
1.0 0.0717288139394


0.0

In [40]:
train_set.plot(title = 'RMS Error', style=['-','--'], grid=True, ylim=(0,0.9))
plt.show()

In [43]:
df_ws = DataFrame()

In [45]:
df_ws

Empty DataFrame
Columns: []
Index: []

In [46]:
t = train_set.y

In [47]:
t

0   -0.263050
1    0.447216
2    1.252177
3    0.958030
4    0.813036
5   -0.173796
6   -0.919094
7   -0.688628
8   -0.638265
9    0.071729
Name: y, dtype: float64

In [49]:
phi = DataFrame()

In [53]:
p=t
p.name = 'a'
phi = pd.concat([phi,p],axis=1)

In [54]:
phi

a
0 -0.263050
1  0.447216
2  1.252177
3  0.958030
4  0.813036
5 -0.173796
6 -0.919094
7 -0.688628
8 -0.638265
9  0.071729

In [55]:
np.dot(phi, phi.T)

array([[ 0.06919512, -0.11763992, -0.32938469, -0.25200959, -0.21386878,
         0.04571693,  0.24176746,  0.18114332,  0.16789548, -0.01886824],
       [-0.11763992,  0.20000184,  0.5599931 ,  0.42844623,  0.36360233,
        -0.07772421, -0.4110334 , -0.30796516, -0.28544225,  0.03207825],
       [-0.32938469,  0.5599931 ,  1.56794692,  1.19962362,  1.0180646 ,
        -0.2176231 , -1.15086874, -0.86228388, -0.7992211 ,  0.08981716],
       [-0.25200959,  0.42844623,  1.19962362,  0.91782241,  0.77891307,
        -0.16650169, -0.88052045, -0.65972648, -0.61147766,  0.06871839],
       [-0.21386878,  0.36360233,  1.0180646 ,  0.77891307,  0.66102719,
        -0.14130222, -0.74725663, -0.55987909, -0.51893257,  0.05831809],
       [ 0.04571693, -0.07772421, -0.2176231 , -0.16650169, -0.14130222,
         0.03020499,  0.15973476,  0.11968064,  0.11092785, -0.01246617],
       [ 0.24176746, -0.4110334 , -1.15086874, -0.88052045, -0.74725663,
         0.15973476,  0.8447345 ,  0.632914  

In [57]:
Sample = Series(p,name='a')

In [58]:
Sample

0   -0.263050
1    0.447216
2    1.252177
3    0.958030
4    0.813036
5   -0.173796
6   -0.919094
7   -0.688628
8   -0.638265
9    0.071729
Name: a, dtype: float64

In [59]:
df_ws = DataFrame()

In [60]:
df_ws = df_ws.append(Sample)

In [65]:
df_ws

0         1         2        3         4         5         6  \
a -0.26305  0.447216  1.252177  0.95803  0.813036 -0.173796 -0.919094   

          7         8         9  
a -0.688628 -0.638265  0.071729

In [66]:
df = DataFrame(columns=['Training set','Test set'])

In [67]:
df

Empty DataFrame
Columns: [Training set, Test set]
Index: []